export { default as Email } from "@/components/Email";
export { default as Header } from "@/components/Header";
export { default as Icon } from "@/components/Icons";
export * from "@/components/Motion";
export { default as Contact } from "@/components/sections/Contact";
export { default as Experience } from "@/components/sections/Experience";
export { default as Main } from "@/components/sections/Main";
export { default as Projects } from "@/components/sections/Projects";
export { default as SectionTitle } from "@/components/SectionTitle";
export { default as SendBtn } from "@/components/SendBtn";
export { default as Side } from "@/components/Side";
export { default as Social } from "@/components/Social";
